background_opacity 0.92

background #1a1b26
foreground #c0caf5

color0  #24283b
color1  #ea526e
color2  #83ba48
color3  #d6932f
color4  #5681dd
color5  #9e74ed
color6  #67baea
color7  #c0caf5
color8  #d7dcf4

color8  #3a3f59
color9  #f7768e
color10 #9ece6a
color11 #e0af68
color12 #7aa2f7
color13 #bb9af7
color14 #7dcfff
color15 #c0caf5

cursor_shape underline
