background {
	color = rgba(36, 40, 59, 1)
}
input-field { 
	outline_thickness = 1
	dots_size = 0.4
	dots_rounding = 1
	size = 150, 25
	outer_color = rgba(169, 177, 214, 1)
	inner_color = rgba(26, 27, 38, 0.5)
	fail_text = Error
	check_text = Validating ...
	font_color = rgba(169, 177, 214, 1)
	font_size = 0.4
	font_family = Noto Sans
	fail_color = rgba(247, 118, 142, 1)
	rounding = 0
	position = 0, -150
	align = center
	valign = center
	fade_on_empty = false
	placeholder_text =
}
label {
	text = Hi there, $USER
    	color = rgba(169, 177, 214, 1)
	font_family = Cascadia Code
	position = 0, 160
	halign = center
	valign = center
}
label {
	text = cmd[update:1000] echo "<span foreground='##a9b1d6'>$(date)</span>"
	position = 0, 0
	halign = center
	valign = center
	font_size = 25
	font_family = Cascadia Code
}
